### ISSUE TITLE
Feature request: properly support multi line labels

### ISSUE THREAD

**Issue by mcorossigo** [open-nomie/nomie#77]
Very much like https://github.com/open-nomie/nomie/issues/67 (which BTW came out incredibly well), one line titles can end up being a little too restrictive, but when they overflows they gets eaten by the emoji icon.

![IMG_3727](https://user-images.githubusercontent.com/36412793/68607518-14a06580-04b1-11ea-8118-deed6ce96d8a.PNG)

The emoji icon seems to have a fixed upper margin (or vertical positioning, I have not investigated your implementation) which seems a little wasteful of botton real estate, even with one line titles.

**Comment by brandoncorbin** [comment]
I'll make it so the label is on top of icon.

**Comment by mcorossigo** [comment]
The fix works works fairly well, but unless having the icon in the absolute center is an unmovable design choice, I have a suggestion:

Since `.n-tracker-button` use `display: flex;`, instead of settings the button components with absolute positioning, you can take advantage of the the flex property.

E.g. with this CSS

```css
.n-tracker-button .emoji {
    left: 0;
    right: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1;
    flex: 0;
}

.n-tracker-button footer {
    left: 4px;
    right: 4px;
    text-align: center;
    line-height: 100%;
    font-size: 0.8rem;
    z-index: 2;
}

the result:

```
|Style|Screen|
|---|---|
|`position: absolute`|<img width="607" alt="Schermata 2019-11-12 alle 20 39 25 2" src="https://user-images.githubusercontent.com/36412793/68704680-f740c980-058c-11ea-81a3-9d9b8232fbe4.png">|
|`display: flex` `flex: 0`|<img width="610" alt="Schermata 2019-11-12 alle 20 39 19 2" src="https://user-images.githubusercontent.com/36412793/68704679-f6a83300-058c-11ea-9378-16f1ae3b042b.png">|

Both `.emoji` and `footer` act in a pretty fluid way.
